language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev
script:
- pytest
notifications:
  slack:
    secure: gOWNdcB71q4HqsT8dZXC3pSmIcyc8QyYIRl/Vi1O7wWlZF51oYKflsiUgtL9vKfy9DD526BckiP3vjwqqLwBs9njft2WLYKoyX0d2GvtM5Te+ApZsx7dIOCDxgIYhxXpPG8hjzoBy/fsu+7z5gxsbxTbPbU5wQPw975p3iQY7CWYXABbjKq6FnfYtDpGCuh5SN5QCfMmmsoozHA8x1de1c9xH5dUvEGUgX/g3fXeZbnNZ33vgoEFuNAe/jFxTJ/7YTt/pRGU5f7hHcCpdovbIM63RM0rPjCaSUR9yyDdih7+dOIUPM7OL66z+aEEJfspluGP7am39gu2atFNleufCg1t92+DdQ6f5sx8F47Mfqf7sWQML+9ePYlrPGgt+pfmsCm76hBWNDU2SPwZvnJmSnDq9XR9RAeDgClQhz8A0z3UpE9ROq5FQUYL5bmvLq9k/hpaG6LTNZCtyynUm1SdDH43syaT8hwMDn27u2A84eXH9LzzqZmrMZGnVfyQT7OYKnTaXPh+1lCIZE3EXGiVkZfSZ2NCJUSaT6+upPVpHsmpvFTPMsSSWELgyzUhH1I2rfpOpxO/8BbOtevKssWkk+Q6qYSkL2PSGGq9+OFk6cAADp7T2z7LEYW0Y49oeyoFEKTxLAhaigypT6gfeo9BLH6NCFy5CmCEz/SjlmIdTJw=
    on_success: change
    on_failure: always
