from pygame.locals import *


WINDOW_WIDTH = 960
WINDOW_HEIGHT = 720

TILE_SIZE = 32
TILE_ROWS = 11
TILE_COLUMNS = 4

GRID_ROWS = 10
GRID_COLUMNS = 16
GRID_WIDTH = TILE_SIZE*GRID_COLUMNS
GRID_HEIGHT = TILE_SIZE*GRID_ROWS

KEYS_UP = [K_UP, K_KP7, K_KP8, K_KP9]
KEYS_DOWN = [K_DOWN, K_KP1, K_KP2, K_KP3]
KEYS_LEFT = [K_LEFT, K_KP1, K_KP4, K_KP7]
KEYS_RIGHT = [K_RIGHT, K_KP3, K_KP6, K_KP9]

NUMBER_OF_TREASURES = 10
NUMBER_OF_THINGS = 50
