import config


PLAY_AREA_BASE_RECTANGLE = (0, 0, config.WINDOW_WIDTH * 0.8, config.WINDOW_HEIGHT * 0.8)
SIDEBAR_BASE_RECTANGLE = (config.WINDOW_WIDTH * 0.8, 0, config.WINDOW_WIDTH * 0.2, config.WINDOW_HEIGHT)
INVENTORY_BASE_RECTANGLE = (0, config.WINDOW_HEIGHT * 0.83, config.WINDOW_WIDTH, config.WINDOW_HEIGHT * 0.2)